import type { Project, Task, TeamMember, Activity, DashboardStats, JiraTicket, Sprint, LearningPath, LearningProgress, Certificate, TekyuProject } from '@/types';

export const mockTeamMembers: TeamMember[] = [
  {
    id: '1',
    email: 'charlie@devsecai.io',
    name: 'Charlie Peter',
    role: 'admin',
    department: 'Engineering',
    projects: ['1', '2', '3'],
    tasksCompleted: 47,
    tasksInProgress: 5,
    streak: 12,
    createdAt: new Date('2024-01-15'),
    lastActive: new Date(),
  },
  {
    id: '2',
    email: 'sarah@devsecai.io',
    name: 'Sarah Chen',
    role: 'lead',
    department: 'Security',
    projects: ['1', '2'],
    tasksCompleted: 38,
    tasksInProgress: 3,
    streak: 8,
    createdAt: new Date('2024-02-01'),
    lastActive: new Date(Date.now() - 60000),
  },
  {
    id: '3',
    email: 'mike@devsecai.io',
    name: 'Mike Johnson',
    role: 'member',
    department: 'DevOps',
    projects: ['2', '3'],
    tasksCompleted: 29,
    tasksInProgress: 4,
    streak: 5,
    createdAt: new Date('2024-03-10'),
    lastActive: new Date(Date.now() - 3600000),
  },
  {
    id: '4',
    email: 'emily@devsecai.io',
    name: 'Emily Davis',
    role: 'member',
    department: 'Engineering',
    projects: ['1', '3'],
    tasksCompleted: 22,
    tasksInProgress: 2,
    streak: 3,
    createdAt: new Date('2024-04-05'),
    lastActive: new Date(Date.now() - 7200000),
  },
  {
    id: '5',
    email: 'alex@devsecai.io',
    name: 'Alex Turner',
    role: 'member',
    department: 'Security',
    projects: ['1'],
    tasksCompleted: 15,
    tasksInProgress: 6,
    streak: 7,
    createdAt: new Date('2024-05-20'),
    lastActive: new Date(Date.now() - 120000),
  },
];

export const mockProjects: Project[] = [
  {
    id: '1',
    name: 'DevSecAI Platform v2.0',
    description: 'Major platform upgrade including new AI security features, improved SDLC integration, and enhanced compliance reporting.',
    status: 'active',
    priority: 'critical',
    owner: '1',
    members: ['1', '2', '4', '5'],
    progress: 68,
    startDate: new Date('2024-10-01'),
    dueDate: new Date('2025-02-28'),
    tags: ['platform', 'ai', 'security', 'sdlc'],
    createdAt: new Date('2024-09-15'),
    updatedAt: new Date(),
  },
  {
    id: '2',
    name: 'Security Pipeline Automation',
    description: 'Implementing automated security scanning and remediation workflows for the CI/CD pipeline.',
    status: 'active',
    priority: 'high',
    owner: '2',
    members: ['1', '2', '3'],
    progress: 45,
    startDate: new Date('2024-11-01'),
    dueDate: new Date('2025-01-31'),
    tags: ['automation', 'ci/cd', 'security'],
    createdAt: new Date('2024-10-20'),
    updatedAt: new Date(),
  },
  {
    id: '3',
    name: 'Compliance Dashboard',
    description: 'Building a comprehensive compliance tracking dashboard for EU AI Act, CRA, and DORA requirements.',
    status: 'planning',
    priority: 'medium',
    owner: '3',
    members: ['3', '4'],
    progress: 15,
    startDate: new Date('2025-01-15'),
    dueDate: new Date('2025-04-30'),
    tags: ['compliance', 'dashboard', 'regulations'],
    createdAt: new Date('2024-12-01'),
    updatedAt: new Date(),
  },
  {
    id: '4',
    name: 'API Security Module',
    description: 'Developing advanced API security features including threat detection and rate limiting.',
    status: 'active',
    priority: 'high',
    owner: '2',
    members: ['2', '5'],
    progress: 82,
    startDate: new Date('2024-09-01'),
    dueDate: new Date('2025-01-20'),
    tags: ['api', 'security', 'module'],
    createdAt: new Date('2024-08-15'),
    updatedAt: new Date(),
  },
  {
    id: '5',
    name: 'Documentation Overhaul',
    description: 'Complete rewrite of technical documentation and user guides for all DevSecAI products.',
    status: 'on-hold',
    priority: 'low',
    owner: '4',
    members: ['4'],
    progress: 30,
    startDate: new Date('2024-11-15'),
    dueDate: new Date('2025-03-31'),
    tags: ['documentation', 'guides'],
    createdAt: new Date('2024-11-01'),
    updatedAt: new Date(),
  },
];

export const mockTasks: Task[] = [
  {
    id: '1',
    projectId: '1',
    title: 'Implement AI threat detection algorithm',
    description: 'Develop machine learning model for detecting security threats in code repositories.',
    status: 'in-progress',
    priority: 'critical',
    assignee: '1',
    reporter: '2',
    dueDate: new Date('2025-01-25'),
    tags: ['ai', 'ml', 'security'],
    subtasks: [
      { id: 's1', title: 'Research existing models', completed: true },
      { id: 's2', title: 'Prepare training data', completed: true },
      { id: 's3', title: 'Train model', completed: false },
      { id: 's4', title: 'Validate accuracy', completed: false },
    ],
    comments: [
      { id: 'c1', userId: '2', content: 'Great progress so far!', createdAt: new Date() },
    ],
    createdAt: new Date('2025-01-10'),
    updatedAt: new Date(),
  },
  {
    id: '2',
    projectId: '1',
    title: 'Design new dashboard UI',
    description: 'Create mockups for the updated security dashboard interface.',
    status: 'review',
    priority: 'high',
    assignee: '4',
    reporter: '1',
    dueDate: new Date('2025-01-20'),
    tags: ['ui', 'design'],
    subtasks: [],
    comments: [],
    createdAt: new Date('2025-01-05'),
    updatedAt: new Date(),
  },
  {
    id: '3',
    projectId: '2',
    title: 'Setup GitHub Actions integration',
    description: 'Configure GitHub Actions workflows for automated security scanning.',
    status: 'done',
    priority: 'high',
    assignee: '3',
    reporter: '2',
    dueDate: new Date('2025-01-15'),
    tags: ['github', 'automation'],
    subtasks: [],
    comments: [
      { id: 'c2', userId: '2', content: 'Tested and working perfectly.', createdAt: new Date() },
    ],
    createdAt: new Date('2025-01-02'),
    updatedAt: new Date(),
  },
  {
    id: '4',
    projectId: '2',
    title: 'Implement SAST tool integration',
    description: 'Integrate static application security testing tools into the pipeline.',
    status: 'in-progress',
    priority: 'high',
    assignee: '2',
    reporter: '1',
    dueDate: new Date('2025-01-28'),
    tags: ['sast', 'security', 'integration'],
    subtasks: [
      { id: 's5', title: 'Research SAST tools', completed: true },
      { id: 's6', title: 'Setup SonarQube', completed: true },
      { id: 's7', title: 'Configure rules', completed: false },
    ],
    comments: [],
    createdAt: new Date('2025-01-08'),
    updatedAt: new Date(),
  },
  {
    id: '5',
    projectId: '3',
    title: 'Define compliance requirements',
    description: 'Document all EU AI Act, CRA, and DORA compliance requirements.',
    status: 'todo',
    priority: 'medium',
    assignee: '3',
    reporter: '1',
    dueDate: new Date('2025-02-01'),
    tags: ['compliance', 'documentation'],
    subtasks: [],
    comments: [],
    createdAt: new Date('2025-01-12'),
    updatedAt: new Date(),
  },
  {
    id: '6',
    projectId: '4',
    title: 'API rate limiting implementation',
    description: 'Implement intelligent rate limiting for API endpoints.',
    status: 'in-progress',
    priority: 'high',
    assignee: '5',
    reporter: '2',
    dueDate: new Date('2025-01-22'),
    tags: ['api', 'security'],
    subtasks: [
      { id: 's8', title: 'Design rate limiting algorithm', completed: true },
      { id: 's9', title: 'Implement Redis caching', completed: true },
      { id: 's10', title: 'Add monitoring', completed: false },
    ],
    comments: [],
    createdAt: new Date('2025-01-06'),
    updatedAt: new Date(),
  },
  {
    id: '7',
    projectId: '1',
    title: 'Write unit tests for security module',
    description: 'Create comprehensive unit tests for the new security scanning module.',
    status: 'todo',
    priority: 'medium',
    assignee: '4',
    reporter: '2',
    dueDate: new Date('2025-01-30'),
    tags: ['testing', 'security'],
    subtasks: [],
    comments: [],
    createdAt: new Date('2025-01-14'),
    updatedAt: new Date(),
  },
];

export const mockActivities: Activity[] = [
  {
    id: '1',
    userId: '1',
    type: 'task_completed',
    entityType: 'task',
    entityId: '3',
    entityName: 'Setup GitHub Actions integration',
    createdAt: new Date(Date.now() - 1800000),
  },
  {
    id: '2',
    userId: '2',
    type: 'comment_added',
    entityType: 'task',
    entityId: '1',
    entityName: 'Implement AI threat detection algorithm',
    createdAt: new Date(Date.now() - 3600000),
  },
  {
    id: '3',
    userId: '4',
    type: 'task_updated',
    entityType: 'task',
    entityId: '2',
    entityName: 'Design new dashboard UI',
    metadata: { field: 'status', from: 'in-progress', to: 'review' },
    createdAt: new Date(Date.now() - 7200000),
  },
  {
    id: '4',
    userId: '3',
    type: 'project_created',
    entityType: 'project',
    entityId: '3',
    entityName: 'Compliance Dashboard',
    createdAt: new Date(Date.now() - 86400000),
  },
  {
    id: '5',
    userId: '5',
    type: 'member_joined',
    entityType: 'user',
    entityId: '5',
    entityName: 'Alex Turner',
    createdAt: new Date(Date.now() - 172800000),
  },
  {
    id: '6',
    userId: '2',
    type: 'task_created',
    entityType: 'task',
    entityId: '4',
    entityName: 'Implement SAST tool integration',
    createdAt: new Date(Date.now() - 259200000),
  },
  {
    id: '7',
    userId: '1',
    type: 'task_updated',
    entityType: 'task',
    entityId: '6',
    entityName: 'API rate limiting implementation',
    metadata: { field: 'priority', from: 'medium', to: 'high' },
    createdAt: new Date(Date.now() - 345600000),
  },
];

export const mockDashboardStats: DashboardStats = {
  totalProjects: 5,
  activeProjects: 3,
  totalTasks: 7,
  completedTasks: 1,
  teamMembers: 5,
  weeklyProgress: 23,
};

// JIRA Board Data
export const mockSprints: Sprint[] = [
  {
    id: 'sprint-1',
    name: 'Sprint 23 - Security Features',
    goal: 'Complete AI threat detection and API security modules',
    startDate: new Date('2025-01-13'),
    endDate: new Date('2025-01-27'),
    status: 'active',
  },
  {
    id: 'sprint-2',
    name: 'Sprint 24 - Compliance',
    goal: 'Begin compliance dashboard implementation',
    startDate: new Date('2025-01-27'),
    endDate: new Date('2025-02-10'),
    status: 'planning',
  },
];

export const mockJiraTickets: JiraTicket[] = [
  {
    id: 'j1',
    key: 'DEV-101',
    title: 'Implement AI threat detection algorithm',
    description: 'Develop ML model for detecting security threats in code repositories',
    type: 'story',
    status: 'in-progress',
    priority: 'highest',
    assignee: '1',
    reporter: '2',
    projectId: '1',
    storyPoints: 8,
    labels: ['ai', 'ml', 'security'],
    sprint: 'sprint-1',
    dueDate: new Date('2025-01-25'),
    createdAt: new Date('2025-01-10'),
    updatedAt: new Date(),
  },
  {
    id: 'j2',
    key: 'DEV-102',
    title: 'Design new dashboard UI mockups',
    description: 'Create high-fidelity mockups for the security dashboard redesign',
    type: 'task',
    status: 'review',
    priority: 'high',
    assignee: '4',
    reporter: '1',
    projectId: '1',
    storyPoints: 3,
    labels: ['ui', 'design'],
    sprint: 'sprint-1',
    dueDate: new Date('2025-01-20'),
    createdAt: new Date('2025-01-05'),
    updatedAt: new Date(),
  },
  {
    id: 'j3',
    key: 'DEV-103',
    title: 'Fix authentication bypass vulnerability',
    description: 'Critical security fix for OAuth token validation',
    type: 'bug',
    status: 'done',
    priority: 'highest',
    assignee: '2',
    reporter: '5',
    projectId: '1',
    storyPoints: 5,
    labels: ['security', 'critical', 'auth'],
    sprint: 'sprint-1',
    createdAt: new Date('2025-01-08'),
    updatedAt: new Date(),
  },
  {
    id: 'j4',
    key: 'DEV-104',
    title: 'Implement SAST tool integration',
    description: 'Integrate SonarQube and Semgrep into CI/CD pipeline',
    type: 'story',
    status: 'in-progress',
    priority: 'high',
    assignee: '3',
    reporter: '2',
    projectId: '2',
    storyPoints: 5,
    labels: ['sast', 'ci-cd', 'automation'],
    sprint: 'sprint-1',
    dueDate: new Date('2025-01-28'),
    createdAt: new Date('2025-01-08'),
    updatedAt: new Date(),
  },
  {
    id: 'j5',
    key: 'DEV-105',
    title: 'API rate limiting with Redis',
    description: 'Implement distributed rate limiting using Redis cluster',
    type: 'story',
    status: 'in-progress',
    priority: 'high',
    assignee: '5',
    reporter: '2',
    projectId: '4',
    storyPoints: 5,
    labels: ['api', 'redis', 'performance'],
    sprint: 'sprint-1',
    dueDate: new Date('2025-01-22'),
    createdAt: new Date('2025-01-06'),
    updatedAt: new Date(),
  },
  {
    id: 'j6',
    key: 'DEV-106',
    title: 'Write unit tests for security module',
    description: 'Achieve 90% code coverage for the security scanning module',
    type: 'task',
    status: 'todo',
    priority: 'medium',
    assignee: '4',
    reporter: '2',
    projectId: '1',
    storyPoints: 3,
    labels: ['testing', 'quality'],
    sprint: 'sprint-1',
    dueDate: new Date('2025-01-30'),
    createdAt: new Date('2025-01-14'),
    updatedAt: new Date(),
  },
  {
    id: 'j7',
    key: 'DEV-107',
    title: 'Define EU AI Act compliance requirements',
    description: 'Document all compliance requirements for EU AI Act',
    type: 'task',
    status: 'backlog',
    priority: 'medium',
    assignee: '3',
    reporter: '1',
    projectId: '3',
    storyPoints: 3,
    labels: ['compliance', 'documentation'],
    dueDate: new Date('2025-02-01'),
    createdAt: new Date('2025-01-12'),
    updatedAt: new Date(),
  },
  {
    id: 'j8',
    key: 'DEV-108',
    title: 'Setup GitHub Actions workflow',
    description: 'Configure automated security scanning in GitHub Actions',
    type: 'task',
    status: 'done',
    priority: 'high',
    assignee: '3',
    reporter: '2',
    projectId: '2',
    storyPoints: 2,
    labels: ['github', 'automation'],
    sprint: 'sprint-1',
    createdAt: new Date('2025-01-02'),
    updatedAt: new Date(),
  },
  {
    id: 'j9',
    key: 'DEV-109',
    title: 'Memory leak in threat scanner',
    description: 'Scanner process memory grows unbounded after 1000+ scans',
    type: 'bug',
    status: 'todo',
    priority: 'high',
    assignee: '1',
    reporter: '3',
    projectId: '1',
    storyPoints: 3,
    labels: ['bug', 'performance'],
    sprint: 'sprint-1',
    createdAt: new Date('2025-01-16'),
    updatedAt: new Date(),
  },
  {
    id: 'j10',
    key: 'DEV-110',
    title: 'Add dark mode support',
    description: 'Implement system-wide dark mode toggle',
    type: 'story',
    status: 'backlog',
    priority: 'low',
    reporter: '4',
    projectId: '1',
    storyPoints: 2,
    labels: ['ui', 'feature'],
    createdAt: new Date('2025-01-15'),
    updatedAt: new Date(),
  },
];

// Learning Tracker Data
export const mockLearningPaths: LearningPath[] = [
  {
    id: 'lp-1',
    title: 'DevSecOps Fundamentals',
    description: 'Learn the foundations of integrating security into the DevOps pipeline. Covers SAST, DAST, SCA, and security automation.',
    category: 'security',
    difficulty: 'beginner',
    estimatedHours: 20,
    modules: [
      { id: 'm1', title: 'Introduction to DevSecOps', description: 'Understanding the DevSecOps philosophy', type: 'video', duration: 45, resources: [], order: 1 },
      { id: 'm2', title: 'SAST Tools & Techniques', description: 'Static Application Security Testing', type: 'video', duration: 60, resources: [], order: 2 },
      { id: 'm3', title: 'DAST Fundamentals', description: 'Dynamic Application Security Testing', type: 'video', duration: 60, resources: [], order: 3 },
      { id: 'm4', title: 'Hands-on: Setting up Security Pipeline', description: 'Configure a complete security pipeline', type: 'lab', duration: 120, resources: [], order: 4 },
      { id: 'm5', title: 'DevSecOps Quiz', description: 'Test your knowledge', type: 'quiz', duration: 30, resources: [], order: 5 },
    ],
    createdAt: new Date('2024-06-01'),
  },
  {
    id: 'lp-2',
    title: 'AWS Security Specialization',
    description: 'Master AWS security services including IAM, KMS, Security Hub, GuardDuty, and more.',
    category: 'cloud',
    difficulty: 'intermediate',
    estimatedHours: 35,
    modules: [
      { id: 'm6', title: 'IAM Deep Dive', description: 'Advanced IAM policies and best practices', type: 'video', duration: 90, resources: [], order: 1 },
      { id: 'm7', title: 'KMS & Encryption', description: 'Key management and data encryption', type: 'video', duration: 60, resources: [], order: 2 },
      { id: 'm8', title: 'Security Hub & GuardDuty', description: 'AWS security monitoring services', type: 'video', duration: 75, resources: [], order: 3 },
      { id: 'm9', title: 'AWS Security Lab', description: 'Hands-on security configuration', type: 'lab', duration: 180, resources: [], order: 4 },
      { id: 'm10', title: 'AWS Security Assessment', description: 'Final assessment', type: 'quiz', duration: 45, resources: [], order: 5 },
    ],
    createdAt: new Date('2024-07-15'),
  },
  {
    id: 'lp-3',
    title: 'Secure Coding with Python',
    description: 'Learn to write secure Python code. Covers OWASP Top 10, input validation, authentication, and cryptography.',
    category: 'programming',
    difficulty: 'intermediate',
    estimatedHours: 25,
    modules: [
      { id: 'm11', title: 'OWASP Top 10 for Python', description: 'Common vulnerabilities in Python applications', type: 'video', duration: 60, resources: [], order: 1 },
      { id: 'm12', title: 'Input Validation & Sanitization', description: 'Preventing injection attacks', type: 'video', duration: 45, resources: [], order: 2 },
      { id: 'm13', title: 'Authentication & Session Management', description: 'Secure auth patterns', type: 'video', duration: 60, resources: [], order: 3 },
      { id: 'm14', title: 'Cryptography in Python', description: 'Using cryptographic libraries correctly', type: 'video', duration: 75, resources: [], order: 4 },
      { id: 'm15', title: 'Secure Coding Project', description: 'Build a secure web application', type: 'project', duration: 240, resources: [], order: 5 },
    ],
    createdAt: new Date('2024-08-01'),
  },
  {
    id: 'lp-4',
    title: 'Kubernetes Security',
    description: 'Secure your Kubernetes clusters. Covers RBAC, network policies, pod security, and runtime protection.',
    category: 'devops',
    difficulty: 'advanced',
    estimatedHours: 30,
    modules: [
      { id: 'm16', title: 'K8s Security Overview', description: 'Kubernetes security architecture', type: 'video', duration: 60, resources: [], order: 1 },
      { id: 'm17', title: 'RBAC & Service Accounts', description: 'Access control in Kubernetes', type: 'video', duration: 75, resources: [], order: 2 },
      { id: 'm18', title: 'Network Policies', description: 'Securing pod-to-pod communication', type: 'video', duration: 60, resources: [], order: 3 },
      { id: 'm19', title: 'Pod Security Standards', description: 'Securing workloads', type: 'video', duration: 60, resources: [], order: 4 },
      { id: 'm20', title: 'K8s Security Lab', description: 'Secure a vulnerable cluster', type: 'lab', duration: 180, resources: [], order: 5 },
    ],
    createdAt: new Date('2024-09-01'),
  },
  {
    id: 'lp-5',
    title: 'Threat Modeling Masterclass',
    description: 'Learn systematic approaches to identifying and mitigating security threats using STRIDE, PASTA, and Attack Trees.',
    category: 'security',
    difficulty: 'advanced',
    estimatedHours: 20,
    modules: [
      { id: 'm21', title: 'Introduction to Threat Modeling', description: 'Why and when to threat model', type: 'video', duration: 45, resources: [], order: 1 },
      { id: 'm22', title: 'STRIDE Methodology', description: 'Microsoft STRIDE framework', type: 'video', duration: 60, resources: [], order: 2 },
      { id: 'm23', title: 'PASTA Framework', description: 'Process for Attack Simulation', type: 'video', duration: 60, resources: [], order: 3 },
      { id: 'm24', title: 'Attack Trees', description: 'Visual threat analysis', type: 'video', duration: 45, resources: [], order: 4 },
      { id: 'm25', title: 'Threat Modeling Workshop', description: 'Model a real application', type: 'project', duration: 180, resources: [], order: 5 },
    ],
    createdAt: new Date('2024-10-01'),
  },
];

export const mockLearningProgress: LearningProgress[] = [
  { userId: '1', pathId: 'lp-1', completedModules: ['m1', 'm2', 'm3', 'm4', 'm5'], startedAt: new Date('2024-08-01'), completedAt: new Date('2024-09-15'), score: 95 },
  { userId: '1', pathId: 'lp-2', completedModules: ['m6', 'm7', 'm8'], currentModule: 'm9', startedAt: new Date('2024-11-01') },
  { userId: '1', pathId: 'lp-5', completedModules: ['m21', 'm22'], currentModule: 'm23', startedAt: new Date('2025-01-05') },
  { userId: '2', pathId: 'lp-1', completedModules: ['m1', 'm2', 'm3', 'm4', 'm5'], startedAt: new Date('2024-07-01'), completedAt: new Date('2024-08-20'), score: 92 },
  { userId: '2', pathId: 'lp-4', completedModules: ['m16', 'm17', 'm18', 'm19', 'm20'], startedAt: new Date('2024-10-01'), completedAt: new Date('2024-12-01'), score: 88 },
  { userId: '3', pathId: 'lp-1', completedModules: ['m1', 'm2'], currentModule: 'm3', startedAt: new Date('2025-01-02') },
  { userId: '4', pathId: 'lp-3', completedModules: ['m11', 'm12', 'm13'], currentModule: 'm14', startedAt: new Date('2024-12-01') },
  { userId: '5', pathId: 'lp-2', completedModules: ['m6'], currentModule: 'm7', startedAt: new Date('2025-01-10') },
];

export const mockCertificates: Certificate[] = [
  { id: 'cert-1', userId: '1', pathId: 'lp-1', pathTitle: 'DevSecOps Fundamentals', issuedAt: new Date('2024-09-15'), score: 95 },
  { id: 'cert-2', userId: '2', pathId: 'lp-1', pathTitle: 'DevSecOps Fundamentals', issuedAt: new Date('2024-08-20'), score: 92 },
  { id: 'cert-3', userId: '2', pathId: 'lp-4', pathTitle: 'Kubernetes Security', issuedAt: new Date('2024-12-01'), score: 88 },
];

// Tekyu Projects Data
export const mockTekyuProjects: TekyuProject[] = [
  {
    id: 'tp-1',
    name: 'DevSecAI Platform',
    description: 'The Secure SDLC Platform - One app that equips your engineers to build anything securely. Automated security requirements, agnostic DevSecOps visibility, and policy-to-action engine.',
    category: 'security-tools',
    status: 'active',
    techStack: ['Next.js', 'TypeScript', 'Python', 'AWS', 'Terraform', 'PostgreSQL'],
    repoUrl: 'https://github.com/tekyu/devsecai-platform',
    demoUrl: 'https://app.devsecai.io',
    docsUrl: 'https://docs.devsecai.io',
    accessLevel: 'all-employees',
    createdBy: '1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date(),
  },
  {
    id: 'tp-2',
    name: 'Security Pipeline Automation',
    description: 'Automated security scanning and remediation workflows for CI/CD pipelines. Integrates with GitHub Actions, GitLab CI, and Jenkins.',
    category: 'automation',
    status: 'active',
    techStack: ['Python', 'GitHub Actions', 'Docker', 'SonarQube', 'Semgrep'],
    repoUrl: 'https://github.com/tekyu/security-pipeline',
    docsUrl: 'https://docs.devsecai.io/pipeline',
    accessLevel: 'all-employees',
    createdBy: '2',
    createdAt: new Date('2024-03-15'),
    updatedAt: new Date(),
  },
  {
    id: 'tp-3',
    name: 'Compliance Dashboard',
    description: 'Comprehensive compliance tracking for EU AI Act, CRA, DORA, and other regulatory requirements. Real-time compliance scoring and remediation guidance.',
    category: 'security-tools',
    status: 'active',
    techStack: ['React', 'Node.js', 'PostgreSQL', 'Redis', 'AWS Lambda'],
    repoUrl: 'https://github.com/tekyu/compliance-dashboard',
    accessLevel: 'all-employees',
    createdBy: '3',
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date(),
  },
  {
    id: 'tp-4',
    name: 'Threat Modeling Tool',
    description: 'Visual threat modeling application supporting STRIDE, PASTA, and Attack Trees methodologies. Collaborative features for security teams.',
    category: 'security-tools',
    status: 'completed',
    techStack: ['React', 'D3.js', 'Node.js', 'MongoDB'],
    repoUrl: 'https://github.com/tekyu/threat-modeler',
    demoUrl: 'https://threats.devsecai.io',
    accessLevel: 'all-employees',
    createdBy: '1',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-10-15'),
  },
  {
    id: 'tp-5',
    name: 'AWS Security Baseline',
    description: 'Terraform modules and CloudFormation templates for implementing AWS security best practices. Includes CIS benchmarks and custom security controls.',
    category: 'infrastructure',
    status: 'active',
    techStack: ['Terraform', 'AWS', 'Python', 'CloudFormation'],
    repoUrl: 'https://github.com/tekyu/aws-security-baseline',
    docsUrl: 'https://docs.devsecai.io/aws-baseline',
    accessLevel: 'all-employees',
    createdBy: '2',
    createdAt: new Date('2024-04-01'),
    updatedAt: new Date(),
  },
  {
    id: 'tp-6',
    name: 'Security Training Platform',
    description: 'Interactive security training with hands-on labs, quizzes, and certification tracking. Covers secure coding, cloud security, and DevSecOps.',
    category: 'training',
    status: 'active',
    techStack: ['Next.js', 'TypeScript', 'PostgreSQL', 'Docker', 'Kubernetes'],
    repoUrl: 'https://github.com/tekyu/security-training',
    demoUrl: 'https://learn.devsecai.io',
    accessLevel: 'all-employees',
    createdBy: '4',
    createdAt: new Date('2024-05-01'),
    updatedAt: new Date(),
  },
  {
    id: 'tp-7',
    name: 'API Security Gateway',
    description: 'Intelligent API gateway with threat detection, rate limiting, and security analytics. Protects APIs from OWASP API Top 10 vulnerabilities.',
    category: 'security-tools',
    status: 'active',
    techStack: ['Go', 'Redis', 'PostgreSQL', 'Kubernetes', 'Prometheus'],
    repoUrl: 'https://github.com/tekyu/api-security-gateway',
    docsUrl: 'https://docs.devsecai.io/api-gateway',
    accessLevel: 'all-employees',
    createdBy: '5',
    createdAt: new Date('2024-07-01'),
    updatedAt: new Date(),
  },
  {
    id: 'tp-8',
    name: 'Vulnerability Scanner',
    description: 'Container and infrastructure vulnerability scanner with AI-powered prioritization. Integrates with JIRA and Slack for automated ticketing.',
    category: 'security-tools',
    status: 'active',
    techStack: ['Python', 'Trivy', 'Grype', 'PostgreSQL', 'RabbitMQ'],
    repoUrl: 'https://github.com/tekyu/vuln-scanner',
    accessLevel: 'all-employees',
    createdBy: '2',
    createdAt: new Date('2024-08-01'),
    updatedAt: new Date(),
  },
  {
    id: 'tp-9',
    name: 'Secrets Detection Engine',
    description: 'Real-time secrets detection for Git repositories. Prevents credential leaks with pre-commit hooks and CI/CD integration.',
    category: 'automation',
    status: 'completed',
    techStack: ['Rust', 'Python', 'Git', 'Docker'],
    repoUrl: 'https://github.com/tekyu/secrets-detector',
    docsUrl: 'https://docs.devsecai.io/secrets',
    accessLevel: 'all-employees',
    createdBy: '1',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-11-01'),
  },
  {
    id: 'tp-10',
    name: 'Cyber Agoge Portal',
    description: 'Team progress tracking portal for DevSecAI. Track projects, tasks, and team activity with integrated learning paths.',
    category: 'training',
    status: 'active',
    techStack: ['Next.js', 'TypeScript', 'Tailwind CSS', 'PostgreSQL'],
    repoUrl: 'https://github.com/CharlieAgoge/NewAgoge',
    accessLevel: 'all-employees',
    createdBy: '1',
    createdAt: new Date('2025-01-18'),
    updatedAt: new Date(),
  },
];
