import type { Project, Task, TeamMember, Activity, DashboardStats } from '@/types';

export const mockTeamMembers: TeamMember[] = [
  {
    id: '1',
    email: 'charlie@devsecai.io',
    name: 'Charlie Peter',
    role: 'admin',
    department: 'Engineering',
    projects: ['1', '2', '3'],
    tasksCompleted: 47,
    tasksInProgress: 5,
    streak: 12,
    createdAt: new Date('2024-01-15'),
    lastActive: new Date(),
  },
  {
    id: '2',
    email: 'sarah@devsecai.io',
    name: 'Sarah Chen',
    role: 'lead',
    department: 'Security',
    projects: ['1', '2'],
    tasksCompleted: 38,
    tasksInProgress: 3,
    streak: 8,
    createdAt: new Date('2024-02-01'),
    lastActive: new Date(Date.now() - 60000),
  },
  {
    id: '3',
    email: 'mike@devsecai.io',
    name: 'Mike Johnson',
    role: 'member',
    department: 'DevOps',
    projects: ['2', '3'],
    tasksCompleted: 29,
    tasksInProgress: 4,
    streak: 5,
    createdAt: new Date('2024-03-10'),
    lastActive: new Date(Date.now() - 3600000),
  },
  {
    id: '4',
    email: 'emily@devsecai.io',
    name: 'Emily Davis',
    role: 'member',
    department: 'Engineering',
    projects: ['1', '3'],
    tasksCompleted: 22,
    tasksInProgress: 2,
    streak: 3,
    createdAt: new Date('2024-04-05'),
    lastActive: new Date(Date.now() - 7200000),
  },
  {
    id: '5',
    email: 'alex@devsecai.io',
    name: 'Alex Turner',
    role: 'member',
    department: 'Security',
    projects: ['1'],
    tasksCompleted: 15,
    tasksInProgress: 6,
    streak: 7,
    createdAt: new Date('2024-05-20'),
    lastActive: new Date(Date.now() - 120000),
  },
];

export const mockProjects: Project[] = [
  {
    id: '1',
    name: 'DevSecAI Platform v2.0',
    description: 'Major platform upgrade including new AI security features, improved SDLC integration, and enhanced compliance reporting.',
    status: 'active',
    priority: 'critical',
    owner: '1',
    members: ['1', '2', '4', '5'],
    progress: 68,
    startDate: new Date('2024-10-01'),
    dueDate: new Date('2025-02-28'),
    tags: ['platform', 'ai', 'security', 'sdlc'],
    createdAt: new Date('2024-09-15'),
    updatedAt: new Date(),
  },
  {
    id: '2',
    name: 'Security Pipeline Automation',
    description: 'Implementing automated security scanning and remediation workflows for the CI/CD pipeline.',
    status: 'active',
    priority: 'high',
    owner: '2',
    members: ['1', '2', '3'],
    progress: 45,
    startDate: new Date('2024-11-01'),
    dueDate: new Date('2025-01-31'),
    tags: ['automation', 'ci/cd', 'security'],
    createdAt: new Date('2024-10-20'),
    updatedAt: new Date(),
  },
  {
    id: '3',
    name: 'Compliance Dashboard',
    description: 'Building a comprehensive compliance tracking dashboard for EU AI Act, CRA, and DORA requirements.',
    status: 'planning',
    priority: 'medium',
    owner: '3',
    members: ['3', '4'],
    progress: 15,
    startDate: new Date('2025-01-15'),
    dueDate: new Date('2025-04-30'),
    tags: ['compliance', 'dashboard', 'regulations'],
    createdAt: new Date('2024-12-01'),
    updatedAt: new Date(),
  },
  {
    id: '4',
    name: 'API Security Module',
    description: 'Developing advanced API security features including threat detection and rate limiting.',
    status: 'active',
    priority: 'high',
    owner: '2',
    members: ['2', '5'],
    progress: 82,
    startDate: new Date('2024-09-01'),
    dueDate: new Date('2025-01-20'),
    tags: ['api', 'security', 'module'],
    createdAt: new Date('2024-08-15'),
    updatedAt: new Date(),
  },
  {
    id: '5',
    name: 'Documentation Overhaul',
    description: 'Complete rewrite of technical documentation and user guides for all DevSecAI products.',
    status: 'on-hold',
    priority: 'low',
    owner: '4',
    members: ['4'],
    progress: 30,
    startDate: new Date('2024-11-15'),
    dueDate: new Date('2025-03-31'),
    tags: ['documentation', 'guides'],
    createdAt: new Date('2024-11-01'),
    updatedAt: new Date(),
  },
];

export const mockTasks: Task[] = [
  {
    id: '1',
    projectId: '1',
    title: 'Implement AI threat detection algorithm',
    description: 'Develop machine learning model for detecting security threats in code repositories.',
    status: 'in-progress',
    priority: 'critical',
    assignee: '1',
    reporter: '2',
    dueDate: new Date('2025-01-25'),
    tags: ['ai', 'ml', 'security'],
    subtasks: [
      { id: 's1', title: 'Research existing models', completed: true },
      { id: 's2', title: 'Prepare training data', completed: true },
      { id: 's3', title: 'Train model', completed: false },
      { id: 's4', title: 'Validate accuracy', completed: false },
    ],
    comments: [
      { id: 'c1', userId: '2', content: 'Great progress so far!', createdAt: new Date() },
    ],
    createdAt: new Date('2025-01-10'),
    updatedAt: new Date(),
  },
  {
    id: '2',
    projectId: '1',
    title: 'Design new dashboard UI',
    description: 'Create mockups for the updated security dashboard interface.',
    status: 'review',
    priority: 'high',
    assignee: '4',
    reporter: '1',
    dueDate: new Date('2025-01-20'),
    tags: ['ui', 'design'],
    subtasks: [],
    comments: [],
    createdAt: new Date('2025-01-05'),
    updatedAt: new Date(),
  },
  {
    id: '3',
    projectId: '2',
    title: 'Setup GitHub Actions integration',
    description: 'Configure GitHub Actions workflows for automated security scanning.',
    status: 'done',
    priority: 'high',
    assignee: '3',
    reporter: '2',
    dueDate: new Date('2025-01-15'),
    tags: ['github', 'automation'],
    subtasks: [],
    comments: [
      { id: 'c2', userId: '2', content: 'Tested and working perfectly.', createdAt: new Date() },
    ],
    createdAt: new Date('2025-01-02'),
    updatedAt: new Date(),
  },
  {
    id: '4',
    projectId: '2',
    title: 'Implement SAST tool integration',
    description: 'Integrate static application security testing tools into the pipeline.',
    status: 'in-progress',
    priority: 'high',
    assignee: '2',
    reporter: '1',
    dueDate: new Date('2025-01-28'),
    tags: ['sast', 'security', 'integration'],
    subtasks: [
      { id: 's5', title: 'Research SAST tools', completed: true },
      { id: 's6', title: 'Setup SonarQube', completed: true },
      { id: 's7', title: 'Configure rules', completed: false },
    ],
    comments: [],
    createdAt: new Date('2025-01-08'),
    updatedAt: new Date(),
  },
  {
    id: '5',
    projectId: '3',
    title: 'Define compliance requirements',
    description: 'Document all EU AI Act, CRA, and DORA compliance requirements.',
    status: 'todo',
    priority: 'medium',
    assignee: '3',
    reporter: '1',
    dueDate: new Date('2025-02-01'),
    tags: ['compliance', 'documentation'],
    subtasks: [],
    comments: [],
    createdAt: new Date('2025-01-12'),
    updatedAt: new Date(),
  },
  {
    id: '6',
    projectId: '4',
    title: 'API rate limiting implementation',
    description: 'Implement intelligent rate limiting for API endpoints.',
    status: 'in-progress',
    priority: 'high',
    assignee: '5',
    reporter: '2',
    dueDate: new Date('2025-01-22'),
    tags: ['api', 'security'],
    subtasks: [
      { id: 's8', title: 'Design rate limiting algorithm', completed: true },
      { id: 's9', title: 'Implement Redis caching', completed: true },
      { id: 's10', title: 'Add monitoring', completed: false },
    ],
    comments: [],
    createdAt: new Date('2025-01-06'),
    updatedAt: new Date(),
  },
  {
    id: '7',
    projectId: '1',
    title: 'Write unit tests for security module',
    description: 'Create comprehensive unit tests for the new security scanning module.',
    status: 'todo',
    priority: 'medium',
    assignee: '4',
    reporter: '2',
    dueDate: new Date('2025-01-30'),
    tags: ['testing', 'security'],
    subtasks: [],
    comments: [],
    createdAt: new Date('2025-01-14'),
    updatedAt: new Date(),
  },
];

export const mockActivities: Activity[] = [
  {
    id: '1',
    userId: '1',
    type: 'task_completed',
    entityType: 'task',
    entityId: '3',
    entityName: 'Setup GitHub Actions integration',
    createdAt: new Date(Date.now() - 1800000),
  },
  {
    id: '2',
    userId: '2',
    type: 'comment_added',
    entityType: 'task',
    entityId: '1',
    entityName: 'Implement AI threat detection algorithm',
    createdAt: new Date(Date.now() - 3600000),
  },
  {
    id: '3',
    userId: '4',
    type: 'task_updated',
    entityType: 'task',
    entityId: '2',
    entityName: 'Design new dashboard UI',
    metadata: { field: 'status', from: 'in-progress', to: 'review' },
    createdAt: new Date(Date.now() - 7200000),
  },
  {
    id: '4',
    userId: '3',
    type: 'project_created',
    entityType: 'project',
    entityId: '3',
    entityName: 'Compliance Dashboard',
    createdAt: new Date(Date.now() - 86400000),
  },
  {
    id: '5',
    userId: '5',
    type: 'member_joined',
    entityType: 'user',
    entityId: '5',
    entityName: 'Alex Turner',
    createdAt: new Date(Date.now() - 172800000),
  },
  {
    id: '6',
    userId: '2',
    type: 'task_created',
    entityType: 'task',
    entityId: '4',
    entityName: 'Implement SAST tool integration',
    createdAt: new Date(Date.now() - 259200000),
  },
  {
    id: '7',
    userId: '1',
    type: 'task_updated',
    entityType: 'task',
    entityId: '6',
    entityName: 'API rate limiting implementation',
    metadata: { field: 'priority', from: 'medium', to: 'high' },
    createdAt: new Date(Date.now() - 345600000),
  },
];

export const mockDashboardStats: DashboardStats = {
  totalProjects: 5,
  activeProjects: 3,
  totalTasks: 7,
  completedTasks: 1,
  teamMembers: 5,
  weeklyProgress: 23,
};
